version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - ./config:/app/config
    environment:
      RAILS_ENV: development
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: skillrx_development
      DATABASE_PORT: 5432
      DATABASE_HOST: db
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: skillrx_development

volumes:
  db_data:

networks:
  default:
    name: skillrx_network