# Production deployment configuration
service: skillrx-production

# Name of the container image.
image: andremuta/skillrx

# Deploy to production server (update with your production server IP)
servers:
  web:
    - YOUR_PRODUCTION_SERVER_IP

proxy:
  ssl: true
  host: your-production-domain.com

registry:
  username: andremuta
  password:
    - KAMAL_REGISTRY_PASSWORD

# Production environment variables
env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - SECRET_KEY_BASE
  clear:
    RAILS_ENV: production
    AWS_DEFAULT_REGION: us-east-1
    AWS_ACCESS_KEY_ID: production_access_key
    AWS_SECRET_ACCESS_KEY: production_secret_key
    AWS_BUCKET_NAME: skillrx-production
    AWS_ENDPOINT_URL: ""
    AZURE_STORAGE_ACCOUNT_NAME: skillrx-prod
    AZURE_STORAGE_ACCOUNT_KEY: production_azure_key
    AZURE_STORAGE_SHARE_NAME: skillrx-prod
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "skillrx_production_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: ubuntu
  keys_only: true
  keys:
    - ~/.ssh/skillrx_web_production.pem