# Staging deployment configuration
service: skillrx-staging

# Name of the container image.
image: andremuta/skillrx

# Deploy to staging server
servers:
  web:
    - 3.239.195.31

proxy:
  ssl: false
  host: 3.239.195.31

registry:
  username: andremuta
  password:
    - KAMAL_REGISTRY_PASSWORD

# Staging environment variables
env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - SECRET_KEY_BASE
  clear:
    RAILS_ENV: production
    AWS_DEFAULT_REGION: us-east-1
    AWS_ACCESS_KEY_ID: test
    AWS_SECRET_ACCESS_KEY: test
    AWS_BUCKET_NAME: skillrx-staging
    AWS_ENDPOINT_URL: ""
    AZURE_STORAGE_ACCOUNT_NAME: skillrx
    AZURE_STORAGE_ACCOUNT_KEY: skillrx
    AZURE_STORAGE_SHARE_NAME: skillrx
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "skillrx_staging_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: ubuntu
  keys_only: true
  keys:
    - ~/.ssh/skillrx_web_staging.pem