default: &default
  language_files:
    command: LanguageFilesScheduler.new.perform
    queue: default
    schedule: "00 21 * * *" # Every day at 21

development:
  <<: *default

production:
  <<: *default

staging:
  <<: *default

# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
