name: Deploy to Production

on:
  push:
    branches: [ main ]  # Deploy production on main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production  # Require manual approval for production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          andremuta/skillrx:${{ github.sha }}
          andremuta/skillrx:production-latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.1'
        bundler-cache: true

    - name: Install Kamal
      run: gem install kamal

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}" > ~/.ssh/skillrx_web_production.pem
        chmod 600 ~/.ssh/skillrx_web_production.pem

    - name: Deploy to production with Kamal
      env:
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        PRODUCTION_DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
        PRODUCTION_SECRET_KEY_BASE: ${{ secrets.PRODUCTION_SECRET_KEY_BASE }}
        PRODUCTION_RAILS_MASTER_KEY: ${{ secrets.PRODUCTION_RAILS_MASTER_KEY }}
      run: |
        kamal app boot --destination production --version ${{ github.sha }}