name: Deploy to Staging

on:
  push:
    branches: [ develop ]  # or whatever branch you want to trigger staging
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          andremuta/skillrx:${{ github.sha }}
          andremuta/skillrx:staging-latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.1'
        bundler-cache: true

    - name: Install Kamal
      run: gem install kamal

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.STAGING_SSH_PRIVATE_KEY }}" > ~/.ssh/skillrx_web_staging.pem
        chmod 600 ~/.ssh/skillrx_web_staging.pem

    - name: Deploy to staging with Kamal
      env:
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        STAGING_DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
        STAGING_SECRET_KEY_BASE: ${{ secrets.STAGING_SECRET_KEY_BASE }}
        STAGING_RAILS_MASTER_KEY: ${{ secrets.STAGING_RAILS_MASTER_KEY }}
      run: |
        kamal app boot --destination staging --version ${{ github.sha }}